### ISSUE TITLE
Schema suggestions

### ISSUE THREAD

**Issue by jpmckinney** [OpenSourceOrg/licenses#16]
* Schema.org uses [keywords](http://schema.org/keywords) instead of `tags`.
* `media_type` would technically be more correct than `content_type` (Content-Type is just an HTTP Header, but media type is how IANA, etc. refer to these).
* Not sure if `name` (under `text`) should be `title` instead (i.e. Dublin Core's term).

**Comment by paultag** [comment]
@jpmckinney Awesome, thanks for this! I think I'll update those! Sad to see `content_type`, but your point makes sense. Does `keywords` carry any semantic meaning I should be aware of?

**Comment by jpmckinney** [comment]
I think it means what you mean by `tags`.
