### ISSUE TITLE
Use JSON data from SPDX website rather than scraping the HTML

### ISSUE THREAD

**Issue by goneall** [OpenSourceOrg/licenses#35]
The SPDX license data is now available in JSON format.  The HTML for the SPDX website is subject to change and may break the current implementation.

spdx.org/licenses/licenses.json contains a summary table of contents for all SPDX licenses.

There is one JSON file for every license on the website in the form spdx.org/licenses/spdx-id.json.

These license JSON files contain all the metadata and text that is tracked in the SPDX text.

All tag names match the SPDX tag/value definitions in the SPDX 2.0 specification.

**Comment by paultag** [comment]
Great idea! Thanks for the bug! Mind sending a PR?

**Comment by goneall** [comment]
Unfortunately, I'm not much of a Python guru - I can take a stab at it if you don't mind doing a good review of the pull request before accepting it.

**Comment by paultag** [comment]
Of course! :D

**Comment by goneall** [comment]
Pull request created

**Comment by goneall** [comment]
@paultag Hi Paul - could you look at the pull request I submitted last week?  Thanks,
Gary

**Comment by paultag** [comment]
Merged, thanks a ton!!
