### ISSUE TITLE
Compilation issues with python 2.7  

### ISSUE THREAD

**Issue by sara-02** [OpenSourceOrg/licenses#40]
```
File "compile.py", line 42
    yield from map(cleanup, json.load(fd))
             ^
SyntaxError: invalid syntax
```

**Comment by paultag** [comment]
@sara-02 Thanks for the bug!

Yeah, this code is in Python 3, does your platform support Python 3?

**Comment by sara-02** [comment]
Yes it does. Got the code running, but the version should be mentioned somewhere in the requirements or the contribution file.

**Comment by paultag** [comment]
@sara-02 Yeah, totally. Sorry about that! 

It used to say it was Python 3 only if you ran it (https://github.com/OpenSourceOrg/licenses/blob/master/compile.py#L24-L26), but the syntax error hides that :)

Sounds great, I'll send changes up for your review shortly!

**Comment by paultag** [comment]
Thanks again!
