### ISSUE TITLE
legally-significant MPL formatting lost

### ISSUE THREAD

**Issue by tieguy** [OpenSourceOrg/licenses#45]
The [official text version](https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt) of the MPL adds 

> \*************
> \* emphasis *
> \*************

to Sections 6 and 7, to avoid the use of ALL CAPS. ([rationale](http://lu.is/blog/2012/08/19/a-quick-note-on-conspicuous-text-also-known-as-all-caps/))

I'm not quite sure how best to capture this in the OSI repo - thoughts?

**Comment by tianon** [comment]
I'm not a maintainer (so take my thoughts for what they're worth), but PRs have been made (and accepted) in the past to replace the `texts/plain/*` files with canonical upstream texts, so simply replacing `texts/plain/MPL-2.0` with the canonical upstream plain-text version might be met favorably. :smile:

**Comment by tieguy** [comment]
Ah! I thought about that, but given the different formatting otherwise I wasn't sure.

**Comment by paultag** [comment]
Nice call @tianon!
