### ISSUE TITLE
OPL-2.1 metadata doesn't contain a link to it's page on opensource.org

### ISSUE THREAD

**Issue by abenkovskii** [OpenSourceOrg/licenses#48]
The entry for the OSET Foundation Public License (OPL-2.1) aka OSET Public License version 2.1 in the json returned by the https://api.opensource.org/licenses/ API endpoint doesn't contain a reference to this page on the OSI site https://opensource.org/licenses/OPL-2.1 in it's "links" field.

I'm posting this report here because this OSI blog post https://opensource.org/node/822 said that the API uses your data as the source.

Is my understanding correct or are this two separate licenses?

**Comment by paultag** [comment]
I think that one was because I had it in the data before it was up on the site. Want to send a PR?
