### ISSUE TITLE
Why is BSD-4 tagged as osi-approved?

### ISSUE THREAD

**Issue by abenkovskii** [OpenSourceOrg/licenses#50]
The BSD 4-Clause License is absent form the lists published on the OSI site https://opensource.org/licenses/alphabetical https://opensource.org/licenses/do-not-use and it's page on the site https://opensource.org/licenses/BSD-4-Clause is broken (if it ever existed at all), but is present in your database and tagged as "osi-approved".

**Comment by paultag** [comment]
A great question @abenkovskii - come to think of it, I might have been prototyping with random data early on and I never checked the ones I was noodling on were actually OSI approved. I've never thought critically about that, nice point. I'm going to remove BSD-4 from the license dump and API

**Comment by paultag** [comment]
Deployed, thanks!
