### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by sunit4155** [OpenSourceOrg/licenses#60]
This is B.S I get hacked everyday I understand the concept of open source but when people fraudulently hard fork on a regular basis just to get into the backend to "PLAYAROUND" its ridiculous licenses,projects BIt coin god forbid I accuire  bit coins nobody seems to care about personal space. I could give a damn about anybody's project. It is already reported to the F.B.I and I'm sick of it. I am just angry I don't mean to come off like a a** but this is ridiculous please if you guys there at GitHub could maybe give me suggestion on what I can do to make this situation a little easier it would be awesome these projects some of them are linked to the Government and I don't mind sharing as long as its reasonable as long as they are using it to better themselves not maliciously to hurt people and infringe on fundamental privacy issues.

**Comment by paultag** [comment]
Thanks for your feedback!
