### ISSUE TITLE
Is the repo still maintained?

### ISSUE THREAD

**Issue by goneall** [OpenSourceOrg/licenses#61]
I have a rather old [request to use this API as a source for the OSI approved flag](https://github.com/spdx/LicenseListPublisher/issues/20) in the SPDX license list.

After looking closely at the data, there are some inconsistencies between the website and the datafile.

If this is being maintained, I can work on a pull request.

BTW - it would be fantastic if there was an authoritative machine readable format for the OSI license information.

**Comment by smaffulli** [comment]
Hi @goneall, this repository is being maintained. @webmink and I are watching it :) I'd love to look over your pull request.

**Comment by goneall** [comment]
@smaffulli Thanks for the response - glad to see the activity.  Before I put in a PR, I just wanted to make sure @webmink or you had the bandwidth to review and merge.  In looking at the open and closed PR's, it looks like none of the PR's have been merged since April 2017.  

I did outline all of the issues I would like to fix in issue #62.  The PR will take some effort.  If there is bandwidth, I will certainly look into the code and create a PR to address at least some of the issues in #62.

**Comment by webmink** [comment]
Yes, we are both making this a new priority now @smaffulli is in the saddle as OSI's ED. I believe @paultag will also chip in to get the old PRs merged.

If you would be so kind as to submit several smaller PRs that would be very helpful for getting them reviewed and merged quickly - thanks!

**Comment by goneall** [comment]
> Yes, we are both making this a new priority now @smaffulli is in the saddle as OSI's ED. I believe @paultag will also chip in to get the old PRs merged.

@webmink That's great news!  I start looking into the PR's.

**Comment by goneall** [comment]
I think this question has been answered - I'll go ahead and close it and open PR's and log new issues for any additional questions I have.
