### ISSUE TITLE
Unable to access https://api.opensource.org Origin DNS error 1016

### ISSUE THREAD

**Issue by max-ieremenko** [OpenSourceOrg/licenses#80]
Unable to access https://api.opensource.org/ 

Error 1016 Ray ID: 70b29532094d91f9 • 2022-05-14 09:24:47 UTC
Origin DNS error

Cloudflare is currently unable to resolve your requested domain (api.opensource.org). 

![error](https://user-images.githubusercontent.com/37539260/168420026-260e65d2-a263-49f0-9718-74a90c2d5450.png)

**Comment by webmink** [comment]
Thanks for the report. The API service is still experimental and was affected by an infrastructure change. We're exploring how to get it back online.

**Comment by webmink** [comment]
OK, all the endpoints in https://github.com/OpenSourceOrg/api/blob/master/doc/endpoints.md are working for me. If you still see a problem please re-open.
