### ISSUE TITLE
Motosoto license text is incomplete

### ISSUE THREAD

**Issue by nicoroeser** [OpenSourceOrg/licenses#86]
The Motosoto license is missing some text. You can see that <https://opensource.org/license/motosoto-php/> and in `texts/plain/Motosoto`.

I assume the issue originates from an encoding problem with one character in the license text. Compare the Jabber Open Source License, version 1.0 on which `Motosoto` is said to be based: the [copy at OSI](https://opensource.org/license/jabberpl-php/) looks OK (perhaps offending character removed?), and the [copy in the FSF Directory](https://directory.fsf.org/wiki/License:JOSL-1.0) has a “Õ” in the place where the Motosoto license text ends.

Given the text of the Jabber Open Source License, version 1.0, I assume that the Motosoto license is missing several paragraphs.

The problem has always been there, see commit 7f06e6a6eed98ecca20ed4fd02d06f3496a78c49, which added the Motosoto license text.

**Comment by nicoroeser** [comment]
The mailing list posting with the [request for approval](https://lists.opensource.org/pipermail/license-discuss_lists.opensource.org/2001-May/003732.html) from 2001-05-23 contains an attached [license document](https://lists.opensource.org/pipermail/license-discuss_lists.opensource.org/attachments/20010523/0b4fe22f/attachment.htm) (HTML document).

**Comment by smaffulli** [comment]
@nicoroeser can you please be more precise for where you see the issue? I checked the files in the repository and I can't find where the text of the Motosoto license is not complete.

https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/Motosoto#L4
https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/licenses/autogenerated/Motosoto.json#L4

**Comment by nicoroeser** [comment]
The [Motosoto license file](https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/Motosoto), which you mentioned, has 10 sections. Compare that to the [Jabber Open Source License file](https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/jabberpl), which has 15 numbered sections, an exhibit A, and further paragraphs.

Particularly have a look at the last section, specifically the last lines, of the Motosoto license text:

https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/Motosoto#L394-L410

**(file ends here!)**

… and the corresponding part in `jabberpl`:

https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/jabberpl#L100-L102

**(license text does _not_ end here!)**

Note that the Motosoto license file does not end with a full stop (or other punctuation mark). This is not a clear indication that something is missing, but looks wrong. Read the last sentence. Well, it makes some sense, but sounds strange, and feels incomplete when comparing it to the common wordings used in that context in other licenses (e.g. most of them have the word “negligence” somewhere nearby).

Use something like `wdiff -n jabberpl Motosoto | colordiff | less -R`, for example, for a detailed comparison between the licenses stored in the repository.

Compare the current Motosoto license document in the repository to the version that had originally been sent in, see [my previous comment](#issuecomment-1546702969). I know that is an earlier version, before feedback had been integrated, but it is unlikely that large parts of text should have been removed.

Note the following forward references in the Motosoto license text:
* [the end of the preamble](https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/Motosoto#L79-L81) refers to “a Glossary at the end of the License”, but it is not there;
* [section 4.e](https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/Motosoto#L241-L243) as well as [section 6](https://github.com/OpenSourceOrg/licenses/blob/3a3f4efde5021129e3089864cac6e94337413b4f/texts/plain/Motosoto#L300-L303) mention “Exhibit A”, but such an exhibit is not contained in the document.

**Comment by jlovejoy** [comment]
@smaffulli - I think what @nicoroeser is trying to point out is the the text that appears on the OSI site at https://opensource.org/license/motosoto-php/ for the Motosoto license does not match (b/c it's missing some of the last sections) what was submitted back in 2001 at https://lists.opensource.org/pipermail/license-discuss_lists.opensource.org/2001-May/003732.html

**Comment by smaffulli** [comment]
https://opensource.org/license/motosoto/ the page has been updated

**Comment by nicoroeser** [comment]
Thank you for the update, @smaffulli !

Now that web page shows a different license version in the page header block (“Version 0.9.1”) and the license text (“Version 0.9”). Would you be so kind and look at the situation again and make another correction accordingly? I don’t know whether OSI has approved version 0.9 or 0.9.1, but I assume that the stated versions should at least be identical in both places?

**Comment by smaffulli** [comment]
thanks, the version that was submitted is 0.9, as seen here: https://lists.opensource.org/pipermail/license-discuss_lists.opensource.org/2001-May/003732.html. I fixed the metadata of the license page.

**Comment by jlovejoy** [comment]
ah, wish I'd seen this sooner!  now making updates on SPDX side at https://github.com/spdx/license-list-XML/pull/2574

would note that the numbering on https://opensource.org/license/motosoto seems to not be sequential (this really threw me off at first!)  FYI @smaffulli
